version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: lucide-react
      - dependency-name: eslint
      - dependency-name: typescript
      - dependency-name: cross-env
