/**
 * Minimal Lucide set for SubPageHero and DynamicIcon
 * @generated by scripts/generate-lucide-registry.mjs — do not edit manually
 */
'use client';

import type { LucideIcon } from 'lucide-react';
import {
  BookOpen,
  CheckCircle,
  Clock,
  DiscAlbum,
  Flame,
  HandHeart,
  HelpCircle,
  Play,
  Sparkles,
  Star,
  TrendingUp,
  Trophy,
  Users,
  Zap,
} from 'lucide-react';

export const SUBPAGE_ICON_REGISTRY = {
  BookOpen,
  CheckCircle,
  Clock,
  DiscAlbum,
  Flame,
  HandHeart,
  HelpCircle,
  Play,
  Sparkles,
  Star,
  TrendingUp,
  Trophy,
  Users,
  Zap,
} as const satisfies Record<string, LucideIcon>;

export type SubPageLucideIconName = keyof typeof SUBPAGE_ICON_REGISTRY;

export function isSubPageLucideIconName(name: string): name is SubPageLucideIconName {
  return name in SUBPAGE_ICON_REGISTRY;
}
