import {
  Archive,
  BadgeCheck,
  Ban,
  DoorClosed,
  DoorOpen,
  Download,
  Eye,
  Flag,
  Heart,
  Info,
  Link,
  ListPlus,
  Mail,
  MessageSquareReply,
  PauseCircle,
  Pencil,
  PlayCircle,
  Share2,
  Star,
  StarOff,
  ToggleLeft,
  Trash2,
  Unlink,
  UserCheck,
  UserPlus,
  XCircle,
  type LucideIcon,
} from 'lucide-react';

export const actionMenuIcons = {
  edit: Pencil,
  delete: Trash2,
  approve: BadgeCheck,
  reject: XCircle,
  suspend: PauseCircle,
  unsuspend: PlayCircle,
  blacklist: Ban,
  removeFromBlacklist: UserCheck,
  linkArtist: Link,
  unlinkArtist: Unlink,
  linkVendor: Link,
  unlinkVendor: Unlink,
  linkPastor: Link,
  unlinkPastor: Unlink,
  answer: MessageSquareReply,
  toggleActive: ToggleLeft,
  toggleFeatured: Star,
  unfeature: StarOff,
  view: Eye,
  viewDetails: Eye,
  share: Share2,
  download: Download,
  favorite: Heart,
  addToPlaylist: ListPlus,
  report: Flag,
  resendInvite: Mail,
  open: DoorOpen,
  close: DoorClosed,
  assignPastor: UserPlus,
  setInactive: Ban,
  archive: Archive,
  viewEmail: Mail,
  rowDetailsHint: Info,
} as const satisfies Record<string, LucideIcon>;
