/**
 * Unified Music Item Type
 * This type represents all music items across different sections.
 * Items are marked with flags (isTrending, isChart, isRecent, isFeaturedArtist) to indicate
 * which sections they belong to.
 */
export interface MusicItem {
  _id: string;
  /** URL slug from API (for download redirect path). */
  slug?: string;
  title: string;
  /** Artist profile _id (e.g. 'ap-1'). Getters populate to { _id, name }. */
  artist: string;
  cover: string;
  category:
    | 'afrobeats'
    | 'hiphop'
    | 'pop'
    | 'rnb'
    | 'gospel'
    | 'instrumental'
    | 'acoustic'
    | 'worship'
    | 'spoken'
    | 'sermon';
  // Trending Song fields
  plays?: string;
  duration?: string;
  isNew?: boolean;
  // Chart Song fields
  rank?: number;
  trend?: 'up' | 'down' | 'same';
  change?: number;
  chartPeriod?: 'weekly' | 'monthly' | 'alltime';
  // Recent Upload fields
  uploadedAt?: string;
  genre?: string;
  // Featured Artist fields
  name?: string; // For artists, name is the same as artist
  image?: string; // For artists, image is the same as cover
  followers?: string;
  verified?: boolean;
  songs?: number;
  // Section flags
  isTrending?: boolean;
  isChart?: boolean;
  isRecent?: boolean;
  isFeaturedArtist?: boolean;
  // Detail page fields
  audioUrl?: string; // For streaming
  downloadUrl?: string; // For downloads
  lyrics?: string; // Song lyrics
  description?: string; // Song description
  isMonetizable?: boolean;
  /** Purchase price when monetizable (NGN). */
  price?: number;
  /** @deprecated Use price */
  downloadPrice?: number;
  releaseDate?: string; // Release date
  tags?: string[]; // Tags for related content
}

/**
 * Central array of all music items
 * Items can appear in multiple sections by setting multiple flags
 * At least 2 items per category are included
 */
export const MUSIC_ITEMS: MusicItem[] = [
  // Afrobeats - Trending Songs
  {
    _id: '1',
    title: 'Sunset Vibes',
    artist: 'ap-1',
    cover: '/images/album-1.jpg',
    category: 'afrobeats',
    plays: '2.4M',
    duration: '3:45',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 1,
    trend: 'up',
    change: 12,
    audioUrl: 'https://example.com/audio/sunset-vibes.mp3',
    downloadUrl: 'https://example.com/downloads/sunset-vibes.mp3',
    description: 'An uplifting afrobeats track that captures the essence of golden hour vibes.',
    lyrics:
      'Sunset vibes, golden skies\nFeel the rhythm, let it rise\nDancing under stars so bright\nMusic takes us through the night',
    releaseDate: '2025-01-15',
    tags: ['afrobeats', 'upbeat', 'dance'],
    isMonetizable: false,
  },
  {
    _id: '2',
    title: 'African Rhythm',
    artist: 'ap-2',
    cover: '/images/album-2.jpg',
    category: 'afrobeats',
    plays: '1.5M',
    duration: '4:20',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 5,
    trend: 'up',
    change: 8,
    audioUrl: 'https://example.com/audio/african-rhythm.mp3',
  },
  // Afrobeats - Recent Uploads
  {
    _id: '3',
    title: 'Lagos Nights',
    artist: 'ap-1',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'afrobeats',
    uploadedAt: '3 hours ago',
    genre: 'Afrobeats',
    isRecent: true,
    audioUrl: 'https://example.com/audio/lagos-nights.mp3',
  },
  {
    _id: '4',
    title: 'Dancehall Vibes',
    artist: 'ap-1',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'afrobeats',
    uploadedAt: '5 hours ago',
    genre: 'Afrobeats',
    isRecent: true,
    audioUrl: 'https://example.com/audio/dancehall-vibes.mp3',
  },
  // Afrobeats - Featured Artists
  {
    _id: '5',
    title: 'DJ Flame',
    name: 'DJ Flame',
    artist: 'ap-1',
    cover: '/images/artist-1.jpg',
    image: '/images/artist-1.jpg',
    category: 'afrobeats',
    genre: 'Afrobeats',
    followers: '125K',
    verified: true,
    songs: 45,
    isFeaturedArtist: true,
  },
  {
    _id: '6',
    title: 'Kofi Beats',
    name: 'Kofi Beats',
    artist: 'ap-2',
    cover: '/images/artist-2.jpg',
    image: '/images/artist-2.jpg',
    category: 'afrobeats',
    genre: 'Afrobeats',
    followers: '98K',
    verified: true,
    songs: 32,
    isFeaturedArtist: true,
  },

  // Hip-Hop - Trending Songs
  {
    _id: '7',
    title: 'Street Dreams',
    artist: 'ap-4',
    cover: '/images/artist-3.jpg',
    category: 'hiphop',
    plays: '654K',
    duration: '3:32',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 6,
    trend: 'up',
    change: 5,
    audioUrl: 'https://example.com/audio/street-dreams.mp3',
  },
  {
    _id: '8',
    title: 'Urban Flow',
    artist: 'ap-2',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'hiphop',
    plays: '890K',
    duration: '3:55',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 4,
    trend: 'up',
    change: 10,
    audioUrl: 'https://example.com/audio/urban-flow.mp3',
  },
  // Hip-Hop - Recent Uploads
  {
    _id: '9',
    title: 'City Lights',
    artist: 'ap-5',
    cover: '/images/album-2.jpg',
    category: 'hiphop',
    uploadedAt: '4 hours ago',
    genre: 'Hip-Hop',
    isRecent: true,
    audioUrl: 'https://example.com/audio/city-lights.mp3',
  },
  {
    _id: '10',
    title: 'Rap Flow',
    artist: 'ap-2',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'hiphop',
    uploadedAt: '7 hours ago',
    genre: 'Hip-Hop',
    isRecent: true,
    audioUrl: 'https://example.com/audio/rap-flow.mp3',
  },
  // Hip-Hop - Featured Artists
  {
    _id: '11',
    title: 'Marcus Jay',
    name: 'Marcus Jay',
    artist: 'ap-3',
    cover: '/images/artist-1.jpg',
    image: '/images/artist-1.jpg',
    category: 'hiphop',
    genre: 'Hip-Hop',
    followers: '87K',
    verified: false,
    songs: 28,
    isFeaturedArtist: true,
  },
  {
    _id: '12',
    title: 'King Vibe',
    name: 'King Vibe',
    artist: 'ap-4',
    cover: '/images/artist-3.jpg',
    image: '/images/artist-3.jpg',
    category: 'hiphop',
    genre: 'Hip-Hop',
    followers: '76K',
    verified: true,
    songs: 35,
    isFeaturedArtist: true,
  },

  // Pop - Trending Songs
  {
    _id: '13',
    title: 'City Lights',
    artist: 'ap-5',
    cover: '/images/album-2.jpg',
    category: 'pop',
    plays: '1.8M',
    duration: '4:12',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 2,
    trend: 'up',
    change: 8,
    audioUrl: 'https://example.com/audio/city-lights-pop.mp3',
  },
  {
    _id: '14',
    title: 'Summer Feels',
    artist: 'ap-5',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'pop',
    plays: '1.2M',
    duration: '3:50',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 7,
    trend: 'up',
    change: 15,
    audioUrl: 'https://example.com/audio/summer-feels.mp3',
  },
  // Pop - Recent Uploads
  {
    _id: '15',
    title: 'Golden Hour',
    artist: 'ap-6',
    cover: '/images/artist-2.jpg',
    category: 'pop',
    uploadedAt: '12 hours ago',
    genre: 'Pop',
    isRecent: true,
    audioUrl: 'https://example.com/audio/golden-hour.mp3',
  },
  {
    _id: '16',
    title: 'Neon Nights',
    artist: 'ap-5',
    cover: '/images/album-2.jpg',
    category: 'pop',
    uploadedAt: '1 day ago',
    genre: 'Pop',
    isRecent: true,
    audioUrl: 'https://example.com/audio/neon-nights.mp3',
  },
  // Pop - Featured Artists
  {
    _id: '17',
    title: 'Luna Belle',
    name: 'Luna Belle',
    artist: 'ap-5',
    cover: '/images/artist-2.jpg',
    image: '/images/artist-2.jpg',
    category: 'pop',
    genre: 'Pop',
    followers: '98K',
    verified: true,
    songs: 32,
    isFeaturedArtist: true,
  },
  {
    _id: '18',
    title: 'Aria Rose',
    name: 'Aria Rose',
    artist: 'ap-6',
    cover: '/images/album-1.jpg',
    image: '/images/album-1.jpg',
    category: 'pop',
    genre: 'Pop',
    followers: '76K',
    verified: true,
    songs: 41,
    isFeaturedArtist: true,
  },

  // R&B - Trending Songs
  {
    _id: '19',
    title: 'Electric Soul',
    artist: 'ap-3',
    cover: '/images/artist-1.jpg',
    category: 'rnb',
    plays: '980K',
    duration: '3:55',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 4,
    trend: 'down',
    change: 3,
    audioUrl: 'https://example.com/audio/electric-soul.mp3',
  },
  {
    _id: '20',
    title: 'Heart & Soul',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'rnb',
    plays: '756K',
    duration: '4:08',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 8,
    trend: 'up',
    change: 6,
    audioUrl: 'https://example.com/audio/heart-soul.mp3',
  },
  // R&B - Recent Uploads
  {
    _id: '21',
    title: 'Smooth Operator',
    artist: 'ap-3',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'rnb',
    uploadedAt: '1 day ago',
    genre: 'R&B',
    isRecent: true,
    audioUrl: 'https://example.com/audio/smooth-operator.mp3',
  },
  {
    _id: '22',
    title: 'Midnight Love',
    artist: 'ap-3',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'rnb',
    uploadedAt: '2 days ago',
    genre: 'R&B',
    isRecent: true,
    audioUrl: 'https://example.com/audio/midnight-love.mp3',
  },
  // R&B - Featured Artists
  {
    _id: '23',
    title: 'Aria Rose',
    name: 'Aria Rose',
    artist: 'ap-6',
    cover: '/images/album-1.jpg',
    image: '/images/album-1.jpg',
    category: 'rnb',
    genre: 'R&B',
    followers: '76K',
    verified: true,
    songs: 41,
    isFeaturedArtist: true,
  },
  {
    _id: '24',
    title: 'Melody Grace',
    name: 'Melody Grace',
    artist: 'ap-6',
    cover: '/images/artist-2.jpg',
    image: '/images/artist-2.jpg',
    category: 'rnb',
    genre: 'R&B',
    followers: '65K',
    verified: false,
    songs: 28,
    isFeaturedArtist: true,
  },

  // Gospel - Trending Songs
  {
    _id: '25',
    title: 'Praise Anthem',
    artist: 'ap-6',
    cover: '/images/album-3.jpg',
    category: 'gospel',
    plays: '1.1M',
    duration: '4:30',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 3,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/praise-anthem.mp3',
  },
  {
    _id: '26',
    title: 'Heavenly Sound',
    artist: 'ap-6',
    cover: '/images/album-1.jpg',
    category: 'gospel',
    plays: '920K',
    duration: '3:45',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 9,
    trend: 'up',
    change: 4,
    audioUrl: 'https://example.com/audio/heavenly-sound.mp3',
  },
  // Gospel - Recent Uploads
  {
    _id: '27',
    title: 'Worship Song',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'gospel',
    uploadedAt: '6 hours ago',
    genre: 'Gospel',
    isRecent: true,
    audioUrl: 'https://example.com/audio/worship-song.mp3',
  },
  {
    _id: '28',
    title: 'Testimony',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'gospel',
    uploadedAt: '9 hours ago',
    genre: 'Gospel',
    isRecent: true,
    audioUrl: 'https://example.com/audio/testimony.mp3',
  },
  // Gospel - Featured Artists
  {
    _id: '29',
    title: 'King Vibe',
    name: 'King Vibe',
    artist: 'ap-4',
    cover: '/images/artist-3.jpg',
    image: '/images/artist-3.jpg',
    category: 'gospel',
    genre: 'Gospel',
    followers: '58K',
    verified: true,
    songs: 22,
    isFeaturedArtist: true,
  },
  {
    _id: '30',
    title: 'Gospel Choir',
    name: 'Gospel Choir',
    artist: 'ap-6',
    cover: '/images/album-3.jpg',
    image: '/images/album-3.jpg',
    category: 'gospel',
    genre: 'Gospel',
    followers: '45K',
    verified: true,
    songs: 18,
    isFeaturedArtist: true,
  },

  // Instrumental - Trending Songs
  {
    _id: '31',
    title: 'Midnight Dreams',
    artist: 'ap-4',
    cover: '/images/album-3.jpg',
    category: 'instrumental',
    plays: '1.2M',
    duration: '3:28',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 3,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/midnight-dreams.mp3',
  },
  {
    _id: '32',
    title: 'Peaceful Mind',
    artist: 'ap-4',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'instrumental',
    plays: '680K',
    duration: '4:15',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 10,
    trend: 'up',
    change: 7,
    audioUrl: 'https://example.com/audio/peaceful-mind.mp3',
  },
  // Instrumental - Recent Uploads
  {
    _id: '33',
    title: 'Ocean Waves',
    artist: 'ap-5',
    cover: '/images/album-1.jpg',
    category: 'instrumental',
    uploadedAt: '6 hours ago',
    genre: 'Instrumental',
    isRecent: true,
    audioUrl: 'https://example.com/audio/ocean-waves.mp3',
  },
  {
    _id: '34',
    title: 'Meditation Flow',
    artist: 'ap-1',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'instrumental',
    uploadedAt: '10 hours ago',
    genre: 'Instrumental',
    isRecent: true,
    audioUrl: 'https://example.com/audio/meditation-flow.mp3',
  },
  // Instrumental - Featured Artists
  {
    _id: '35',
    title: 'The Wave',
    name: 'The Wave',
    artist: 'ap-4',
    cover: '/images/album-2.jpg',
    image: '/images/album-2.jpg',
    category: 'instrumental',
    genre: 'Instrumental',
    followers: '64K',
    verified: false,
    songs: 53,
    isFeaturedArtist: true,
  },
  {
    _id: '36',
    title: 'Zen Beats',
    name: 'Zen Beats',
    artist: 'ap-4',
    cover: '/images/album-3.jpg',
    image: '/images/album-3.jpg',
    category: 'instrumental',
    genre: 'Instrumental',
    followers: '52K',
    verified: false,
    songs: 38,
    isFeaturedArtist: true,
  },

  // Acoustic - Trending Songs
  {
    _id: '37',
    title: 'Morning Light',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'acoustic',
    plays: '543K',
    duration: '3:18',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 7,
    trend: 'down',
    change: 2,
    audioUrl: 'https://example.com/audio/morning-light.mp3',
  },
  {
    _id: '38',
    title: 'Guitar Serenade',
    artist: 'ap-1',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'acoustic',
    plays: '432K',
    duration: '3:50',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 8,
    trend: 'up',
    change: 20,
    audioUrl: 'https://example.com/audio/guitar-serenade.mp3',
  },
  // Acoustic - Recent Uploads
  {
    _id: '39',
    title: 'Rise Up',
    artist: 'ap-2',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'acoustic',
    uploadedAt: '8 hours ago',
    genre: 'Acoustic',
    isRecent: true,
    audioUrl: 'https://example.com/audio/rise-up.mp3',
  },
  {
    _id: '40',
    title: 'Fingerstyle',
    artist: 'ap-3',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'acoustic',
    uploadedAt: '11 hours ago',
    genre: 'Acoustic',
    isRecent: true,
    audioUrl: 'https://example.com/audio/fingerstyle.mp3',
  },
  // Acoustic - Featured Artists
  {
    _id: '41',
    title: 'Sarah Grace',
    name: 'Sarah Grace',
    artist: 'ap-6',
    cover: '/images/artist-1.jpg',
    image: '/images/artist-1.jpg',
    category: 'acoustic',
    genre: 'Acoustic',
    followers: '42K',
    verified: false,
    songs: 19,
    isFeaturedArtist: true,
  },
  {
    _id: '42',
    title: 'Acoustic Soul',
    name: 'Acoustic Soul',
    artist: 'ap-1',
    cover: '/images/artist-2.jpg',
    image: '/images/artist-2.jpg',
    category: 'acoustic',
    genre: 'Acoustic',
    followers: '38K',
    verified: true,
    songs: 24,
    isFeaturedArtist: true,
  },

  // Worship - Trending Songs
  {
    _id: '43',
    title: 'Holy Spirit',
    artist: 'ap-6',
    cover: '/images/album-2.jpg',
    category: 'worship',
    plays: '1.5M',
    duration: '5:20',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 2,
    trend: 'up',
    change: 9,
    audioUrl: 'https://example.com/audio/holy-spirit.mp3',
  },
  {
    _id: '44',
    title: 'Hallelujah',
    artist: 'ap-4',
    cover: '/images/album-3.jpg',
    category: 'worship',
    plays: '1.0M',
    duration: '4:45',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 5,
    trend: 'up',
    change: 11,
    audioUrl: 'https://example.com/audio/hallelujah.mp3',
  },
  // Worship - Recent Uploads
  {
    _id: '45',
    title: 'Glory Song',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'worship',
    uploadedAt: '2 hours ago',
    genre: 'Worship',
    isRecent: true,
    audioUrl: 'https://example.com/audio/glory-song.mp3',
  },
  {
    _id: '46',
    title: 'Adoration',
    artist: 'ap-4',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'worship',
    uploadedAt: '5 hours ago',
    genre: 'Worship',
    isRecent: true,
    audioUrl: 'https://example.com/audio/adoration.mp3',
  },
  // Worship - Featured Artists
  {
    _id: '47',
    title: 'Worship Team',
    name: 'Worship Team',
    artist: 'ap-6',
    cover: '/images/artist-1.jpg',
    image: '/images/artist-1.jpg',
    category: 'worship',
    genre: 'Worship',
    followers: '95K',
    verified: true,
    songs: 48,
    isFeaturedArtist: true,
  },
  {
    _id: '48',
    title: 'Praise Band',
    name: 'Praise Band',
    artist: 'ap-4',
    cover: '/images/artist-3.jpg',
    image: '/images/artist-3.jpg',
    category: 'worship',
    genre: 'Worship',
    followers: '82K',
    verified: true,
    songs: 36,
    isFeaturedArtist: true,
  },

  // Spoken Word - Trending Songs
  {
    _id: '49',
    title: 'Inspiration',
    artist: 'ap-3',
    cover: '/images/album-1.jpg',
    category: 'spoken',
    plays: '356K',
    duration: '4:00',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 9,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/inspiration.mp3',
  },
  {
    _id: '50',
    title: 'Poetry Flow',
    artist: 'ap-3',
    cover: '/images/album-2.jpg',
    category: 'spoken',
    plays: '298K',
    duration: '3:30',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'weekly',
    rank: 10,
    trend: 'up',
    change: 3,
    audioUrl: 'https://example.com/audio/poetry-flow.mp3',
  },
  // Spoken Word - Recent Uploads
  {
    _id: '51',
    title: 'Motivational Speech',
    artist: 'ap-1',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'spoken',
    uploadedAt: '1 day ago',
    genre: 'Spoken Word',
    isRecent: true,
    audioUrl: 'https://example.com/audio/motivational-speech.mp3',
  },
  {
    _id: '52',
    title: 'Faith Declaration',
    artist: 'ap-2',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'spoken',
    uploadedAt: '2 days ago',
    genre: 'Spoken Word',
    isRecent: true,
    audioUrl: 'https://example.com/audio/faith-declaration.mp3',
  },
  // Spoken Word - Featured Artists
  {
    _id: '53',
    title: 'Word Master',
    name: 'Word Master',
    artist: 'ap-3',
    cover: '/images/artist-2.jpg',
    image: '/images/artist-2.jpg',
    category: 'spoken',
    genre: 'Spoken Word',
    followers: '35K',
    verified: false,
    songs: 15,
    isFeaturedArtist: true,
  },
  {
    _id: '54',
    title: 'Verse Speaker',
    name: 'Verse Speaker',
    artist: 'ap-3',
    cover: '/images/artist-3.jpg',
    image: '/images/artist-3.jpg',
    category: 'spoken',
    genre: 'Spoken Word',
    followers: '28K',
    verified: true,
    songs: 12,
    isFeaturedArtist: true,
  },

  // Sermon - Trending
  {
    _id: '55',
    title: 'Grace Abounding',
    artist: 'ap-1',
    cover: '/images/album-3.jpg',
    category: 'sermon',
    plays: '10K',
    duration: '45:00',
    isNew: true,
    isTrending: true,
    isChart: false,
    chartPeriod: 'weekly',
    rank: 0,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/grace-abounding.mp3',
    description: 'A powerful sermon on grace.',
    releaseDate: '2025-01-20',
    tags: ['sermon', 'grace', 'faith'],
    isMonetizable: false,
  },
  {
    _id: '56',
    title: 'Faith in Hard Times',
    artist: 'ap-2',
    cover: '/images/album-1.jpg',
    category: 'sermon',
    plays: '8K',
    duration: '38:15',
    isNew: false,
    isTrending: true,
    isChart: false,
    audioUrl: 'https://example.com/audio/faith-hard-times.mp3',
    description: 'Encouragement for difficult seasons.',
    releaseDate: '2025-01-10',
    tags: ['sermon', 'faith', 'encouragement'],
    isMonetizable: false,
  },

  // Monthly Chart Songs (duplicates of weekly charts)
  {
    _id: '100',
    title: 'Sunset Vibes',
    artist: 'ap-1',
    cover: '/images/album-1.jpg',
    category: 'afrobeats',
    plays: '2.4M',
    duration: '3:45',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 1,
    trend: 'up',
    change: 12,
    audioUrl: 'https://example.com/audio/sunset-vibes.mp3',
    downloadUrl: 'https://example.com/downloads/sunset-vibes.mp3',
    description: 'An uplifting afrobeats track that captures the essence of golden hour vibes.',
    lyrics:
      'Sunset vibes, golden skies\nFeel the rhythm, let it rise\nDancing under stars so bright\nMusic takes us through the night',
    releaseDate: '2025-01-15',
    tags: ['afrobeats', 'upbeat', 'dance'],
    isMonetizable: false,
  },
  {
    _id: '101',
    title: 'African Rhythm',
    artist: 'ap-2',
    cover: '/images/album-2.jpg',
    category: 'afrobeats',
    plays: '1.5M',
    duration: '4:20',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 5,
    trend: 'up',
    change: 8,
    audioUrl: 'https://example.com/audio/african-rhythm.mp3',
  },
  {
    _id: '102',
    title: 'Street Dreams',
    artist: 'ap-4',
    cover: '/images/artist-3.jpg',
    category: 'hiphop',
    plays: '654K',
    duration: '3:32',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 6,
    trend: 'up',
    change: 5,
    audioUrl: 'https://example.com/audio/street-dreams.mp3',
  },
  {
    _id: '103',
    title: 'Urban Flow',
    artist: 'ap-2',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'hiphop',
    plays: '890K',
    duration: '3:55',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 4,
    trend: 'up',
    change: 10,
    audioUrl: 'https://example.com/audio/urban-flow.mp3',
  },
  {
    _id: '104',
    title: 'City Lights',
    artist: 'ap-5',
    cover: '/images/album-2.jpg',
    category: 'pop',
    plays: '1.8M',
    duration: '4:12',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 2,
    trend: 'up',
    change: 8,
    audioUrl: 'https://example.com/audio/city-lights-pop.mp3',
  },
  {
    _id: '105',
    title: 'Summer Feels',
    artist: 'ap-5',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'pop',
    plays: '1.2M',
    duration: '3:50',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 7,
    trend: 'up',
    change: 15,
    audioUrl: 'https://example.com/audio/summer-feels.mp3',
  },
  {
    _id: '106',
    title: 'Electric Soul',
    artist: 'ap-3',
    cover: '/images/artist-1.jpg',
    category: 'rnb',
    plays: '980K',
    duration: '3:55',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 4,
    trend: 'down',
    change: 3,
    audioUrl: 'https://example.com/audio/electric-soul.mp3',
  },
  {
    _id: '107',
    title: 'Heart & Soul',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'rnb',
    plays: '756K',
    duration: '4:08',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 8,
    trend: 'up',
    change: 6,
    audioUrl: 'https://example.com/audio/heart-soul.mp3',
  },
  {
    _id: '108',
    title: 'Praise Anthem',
    artist: 'ap-6',
    cover: '/images/album-3.jpg',
    category: 'gospel',
    plays: '1.1M',
    duration: '4:30',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 3,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/praise-anthem.mp3',
  },
  {
    _id: '109',
    title: 'Heavenly Sound',
    artist: 'ap-6',
    cover: '/images/album-1.jpg',
    category: 'gospel',
    plays: '920K',
    duration: '3:45',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 9,
    trend: 'up',
    change: 4,
    audioUrl: 'https://example.com/audio/heavenly-sound.mp3',
  },
  {
    _id: '110',
    title: 'Midnight Dreams',
    artist: 'ap-4',
    cover: '/images/album-3.jpg',
    category: 'instrumental',
    plays: '1.2M',
    duration: '3:28',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 3,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/midnight-dreams.mp3',
  },
  {
    _id: '111',
    title: 'Peaceful Mind',
    artist: 'ap-4',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'instrumental',
    plays: '680K',
    duration: '4:15',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 10,
    trend: 'up',
    change: 7,
    audioUrl: 'https://example.com/audio/peaceful-mind.mp3',
  },
  {
    _id: '112',
    title: 'Morning Light',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'acoustic',
    plays: '543K',
    duration: '3:18',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 7,
    trend: 'down',
    change: 2,
    audioUrl: 'https://example.com/audio/morning-light.mp3',
  },
  {
    _id: '113',
    title: 'Guitar Serenade',
    artist: 'ap-1',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'acoustic',
    plays: '432K',
    duration: '3:50',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 8,
    trend: 'up',
    change: 20,
    audioUrl: 'https://example.com/audio/guitar-serenade.mp3',
  },
  {
    _id: '114',
    title: 'Holy Spirit',
    artist: 'ap-6',
    cover: '/images/album-2.jpg',
    category: 'worship',
    plays: '1.5M',
    duration: '5:20',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 2,
    trend: 'up',
    change: 9,
    audioUrl: 'https://example.com/audio/holy-spirit.mp3',
  },
  {
    _id: '115',
    title: 'Hallelujah',
    artist: 'ap-4',
    cover: '/images/album-3.jpg',
    category: 'worship',
    plays: '1.0M',
    duration: '4:45',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 5,
    trend: 'up',
    change: 11,
    audioUrl: 'https://example.com/audio/hallelujah.mp3',
  },
  {
    _id: '116',
    title: 'Inspiration',
    artist: 'ap-3',
    cover: '/images/album-1.jpg',
    category: 'spoken',
    plays: '356K',
    duration: '4:00',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 9,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/inspiration.mp3',
  },
  {
    _id: '117',
    title: 'Poetry Flow',
    artist: 'ap-3',
    cover: '/images/album-2.jpg',
    category: 'spoken',
    plays: '298K',
    duration: '3:30',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'monthly',
    rank: 10,
    trend: 'up',
    change: 3,
    audioUrl: 'https://example.com/audio/poetry-flow.mp3',
  },

  // All-Time Chart Songs (duplicates of weekly charts)
  {
    _id: '200',
    title: 'Sunset Vibes',
    artist: 'ap-1',
    cover: '/images/album-1.jpg',
    category: 'afrobeats',
    plays: '2.4M',
    duration: '3:45',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 1,
    trend: 'up',
    change: 12,
    audioUrl: 'https://example.com/audio/sunset-vibes.mp3',
    downloadUrl: 'https://example.com/downloads/sunset-vibes.mp3',
    description: 'An uplifting afrobeats track that captures the essence of golden hour vibes.',
    lyrics:
      'Sunset vibes, golden skies\nFeel the rhythm, let it rise\nDancing under stars so bright\nMusic takes us through the night',
    releaseDate: '2025-01-15',
    tags: ['afrobeats', 'upbeat', 'dance'],
    isMonetizable: false,
  },
  {
    _id: '201',
    title: 'African Rhythm',
    artist: 'ap-2',
    cover: '/images/album-2.jpg',
    category: 'afrobeats',
    plays: '1.5M',
    duration: '4:20',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 5,
    trend: 'up',
    change: 8,
    audioUrl: 'https://example.com/audio/african-rhythm.mp3',
  },
  {
    _id: '202',
    title: 'Street Dreams',
    artist: 'ap-4',
    cover: '/images/artist-3.jpg',
    category: 'hiphop',
    plays: '654K',
    duration: '3:32',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 6,
    trend: 'up',
    change: 5,
    audioUrl: 'https://example.com/audio/street-dreams.mp3',
  },
  {
    _id: '203',
    title: 'Urban Flow',
    artist: 'ap-2',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'hiphop',
    plays: '890K',
    duration: '3:55',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 4,
    trend: 'up',
    change: 10,
    audioUrl: 'https://example.com/audio/urban-flow.mp3',
  },
  {
    _id: '204',
    title: 'City Lights',
    artist: 'ap-5',
    cover: '/images/album-2.jpg',
    category: 'pop',
    plays: '1.8M',
    duration: '4:12',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 2,
    trend: 'up',
    change: 8,
    audioUrl: 'https://example.com/audio/city-lights-pop.mp3',
  },
  {
    _id: '205',
    title: 'Summer Feels',
    artist: 'ap-5',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'pop',
    plays: '1.2M',
    duration: '3:50',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 7,
    trend: 'up',
    change: 15,
    audioUrl: 'https://example.com/audio/summer-feels.mp3',
  },
  {
    _id: '206',
    title: 'Electric Soul',
    artist: 'ap-3',
    cover: '/images/artist-1.jpg',
    category: 'rnb',
    plays: '980K',
    duration: '3:55',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 4,
    trend: 'down',
    change: 3,
    audioUrl: 'https://example.com/audio/electric-soul.mp3',
  },
  {
    _id: '207',
    title: 'Heart & Soul',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'rnb',
    plays: '756K',
    duration: '4:08',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 8,
    trend: 'up',
    change: 6,
    audioUrl: 'https://example.com/audio/heart-soul.mp3',
  },
  {
    _id: '208',
    title: 'Praise Anthem',
    artist: 'ap-6',
    cover: '/images/album-3.jpg',
    category: 'gospel',
    plays: '1.1M',
    duration: '4:30',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 3,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/praise-anthem.mp3',
  },
  {
    _id: '209',
    title: 'Heavenly Sound',
    artist: 'ap-6',
    cover: '/images/album-1.jpg',
    category: 'gospel',
    plays: '920K',
    duration: '3:45',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 9,
    trend: 'up',
    change: 4,
    audioUrl: 'https://example.com/audio/heavenly-sound.mp3',
  },
  {
    _id: '210',
    title: 'Midnight Dreams',
    artist: 'ap-4',
    cover: '/images/album-3.jpg',
    category: 'instrumental',
    plays: '1.2M',
    duration: '3:28',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 3,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/midnight-dreams.mp3',
  },
  {
    _id: '211',
    title: 'Peaceful Mind',
    artist: 'ap-4',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'instrumental',
    plays: '680K',
    duration: '4:15',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 10,
    trend: 'up',
    change: 7,
    audioUrl: 'https://example.com/audio/peaceful-mind.mp3',
  },
  {
    _id: '212',
    title: 'Morning Light',
    artist: 'ap-6',
    cover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    category: 'acoustic',
    plays: '543K',
    duration: '3:18',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 7,
    trend: 'down',
    change: 2,
    audioUrl: 'https://example.com/audio/morning-light.mp3',
  },
  {
    _id: '213',
    title: 'Guitar Serenade',
    artist: 'ap-1',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop',
    category: 'acoustic',
    plays: '432K',
    duration: '3:50',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 8,
    trend: 'up',
    change: 20,
    audioUrl: 'https://example.com/audio/guitar-serenade.mp3',
  },
  {
    _id: '214',
    title: 'Holy Spirit',
    artist: 'ap-6',
    cover: '/images/album-2.jpg',
    category: 'worship',
    plays: '1.5M',
    duration: '5:20',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 2,
    trend: 'up',
    change: 9,
    audioUrl: 'https://example.com/audio/holy-spirit.mp3',
  },
  {
    _id: '215',
    title: 'Hallelujah',
    artist: 'ap-4',
    cover: '/images/album-3.jpg',
    category: 'worship',
    plays: '1.0M',
    duration: '4:45',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 5,
    trend: 'up',
    change: 11,
    audioUrl: 'https://example.com/audio/hallelujah.mp3',
  },
  {
    _id: '216',
    title: 'Inspiration',
    artist: 'ap-3',
    cover: '/images/album-1.jpg',
    category: 'spoken',
    plays: '356K',
    duration: '4:00',
    isNew: true,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 9,
    trend: 'same',
    change: 0,
    audioUrl: 'https://example.com/audio/inspiration.mp3',
  },
  {
    _id: '217',
    title: 'Poetry Flow',
    artist: 'ap-3',
    cover: '/images/album-2.jpg',
    category: 'spoken',
    plays: '298K',
    duration: '3:30',
    isNew: false,
    isTrending: true,
    isChart: true,
    chartPeriod: 'alltime',
    rank: 10,
    trend: 'up',
    change: 3,
    audioUrl: 'https://example.com/audio/poetry-flow.mp3',
  },
];
