import type { ArtistProfile } from '@/lib/types/artist';

/**
 * Central array of artist profiles (user-linked).
 * Used for rising artists, featured artists on Music/Video pages, and community artist list/detail.
 */
export const ARTIST_PROFILES: ArtistProfile[] = [
  {
    _id: 'ap-1',
    user: 'user-1',
    name: 'DJ Flame',
    genre: 'Afrobeats',
    image: '/images/artist-1.jpg',
    coverImage: '/images/album-1.jpg',
    bio: 'Afrobeats producer and performer. Bringing golden hour vibes to the world.',
    followers: '125K',
    verified: true,
    isFeatured: true,
    isRising: true,
    songs: 45,
    videos: 12,
    socials: {
      instagram: 'https://instagram.com/djflame',
      twitter: 'https://twitter.com/djflame',
      youtube: 'https://youtube.com/djflame',
    },
  },
  {
    _id: 'ap-2',
    user: 'user-2',
    name: 'Kofi Beats',
    genre: 'Afrobeats',
    image: '/images/artist-2.jpg',
    coverImage: '/images/album-2.jpg',
    bio: 'African rhythm and dancehall artist.',
    followers: '98K',
    verified: true,
    isFeatured: true,
    isRising: true,
    songs: 32,
    videos: 8,
    socials: {
      instagram: 'https://instagram.com/kofibeats',
      youtube: 'https://youtube.com/kofibeats',
    },
  },
  {
    _id: 'ap-3',
    user: 'user-3',
    name: 'Marcus Jay',
    genre: 'Hip-Hop',
    image: '/images/artist-1.jpg',
    coverImage: '/images/album-2.jpg',
    bio: 'Hip-hop artist with a message.',
    followers: '87K',
    verified: false,
    isFeatured: true,
    isRising: true,
    songs: 28,
    videos: 5,
    socials: {
      instagram: 'https://instagram.com/marcusjay',
      twitter: 'https://twitter.com/marcusjay',
    },
  },
  {
    _id: 'ap-4',
    user: 'user-4',
    name: 'King Vibe',
    genre: 'Hip-Hop',
    image: '/images/artist-3.jpg',
    coverImage: '/images/artist-3.jpg',
    bio: 'Urban flow and street dreams.',
    followers: '76K',
    verified: true,
    isFeatured: true,
    isRising: true,
    songs: 35,
    videos: 10,
    socials: {
      instagram: 'https://instagram.com/kingvibe',
      youtube: 'https://youtube.com/kingvibe',
    },
  },
  {
    _id: 'ap-5',
    user: 'user-5',
    name: 'Luna Belle',
    genre: 'Pop',
    image: '/images/artist-2.jpg',
    coverImage: '/images/album-2.jpg',
    bio: 'Pop and R&B artist. City lights and summer vibes.',
    followers: '98K',
    verified: true,
    isFeatured: true,
    isRising: false,
    songs: 42,
    videos: 15,
    socials: {
      instagram: 'https://instagram.com/lunabelle',
      twitter: 'https://twitter.com/lunabelle',
      youtube: 'https://youtube.com/lunabelle',
    },
  },
  {
    _id: 'ap-6',
    user: 'user-6',
    name: 'Aria Rose',
    genre: 'Pop',
    image: '/images/album-1.jpg',
    coverImage: '/images/album-1.jpg',
    bio: 'Singer-songwriter. Melodies that move the soul.',
    followers: '76K',
    verified: true,
    isFeatured: true,
    isRising: false,
    songs: 38,
    videos: 9,
    socials: {
      instagram: 'https://instagram.com/ariarose',
      youtube: 'https://youtube.com/ariarose',
    },
  },
];
